/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateRpnArgs } from "./CreateRpnArgs";
import { UpdateRpnArgs } from "./UpdateRpnArgs";
import { DeleteRpnArgs } from "./DeleteRpnArgs";
import { RpnFindManyArgs } from "./RpnFindManyArgs";
import { RpnFindUniqueArgs } from "./RpnFindUniqueArgs";
import { Rpn } from "./Rpn";
import { Product } from "../../product/base/Product";
import { User } from "../../user/base/User";
import { RpnService } from "../rpn.service";

@graphql.Resolver(() => Rpn)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class RpnResolverBase {
  constructor(
    protected readonly service: RpnService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Rpn",
    action: "read",
    possession: "any",
  })
  async _rpnsMeta(
    @graphql.Args() args: RpnFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Rpn])
  @nestAccessControl.UseRoles({
    resource: "Rpn",
    action: "read",
    possession: "any",
  })
  async rpns(
    @graphql.Args() args: RpnFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Rpn[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Rpn",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Rpn, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Rpn",
    action: "read",
    possession: "own",
  })
  async rpn(
    @graphql.Args() args: RpnFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Rpn | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Rpn",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Rpn)
  @nestAccessControl.UseRoles({
    resource: "Rpn",
    action: "create",
    possession: "any",
  })
  async createRpn(
    @graphql.Args() args: CreateRpnArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Rpn> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Rpn",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Rpn"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        productId: {
          connect: args.data.productId,
        },

        userId: args.data.userId
          ? {
              connect: args.data.userId,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Rpn)
  @nestAccessControl.UseRoles({
    resource: "Rpn",
    action: "update",
    possession: "any",
  })
  async updateRpn(
    @graphql.Args() args: UpdateRpnArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Rpn | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Rpn",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Rpn"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          productId: {
            connect: args.data.productId,
          },

          userId: args.data.userId
            ? {
                connect: args.data.userId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Rpn)
  @nestAccessControl.UseRoles({
    resource: "Rpn",
    action: "delete",
    possession: "any",
  })
  async deleteRpn(@graphql.Args() args: DeleteRpnArgs): Promise<Rpn | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Product, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Rpn",
    action: "read",
    possession: "any",
  })
  async productId(
    @graphql.Parent() parent: Rpn,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Product | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Product",
    });
    const result = await this.service.getProductId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Rpn",
    action: "read",
    possession: "any",
  })
  async userId(
    @graphql.Parent() parent: Rpn,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUserId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
